name: first github action
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo Hello, world.
      - name: Install dependencies
        run: pwd
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy
        run: |
          cd dist
          git init
          git add -A
          git commit -m 'deploy'
          git push -f https://github.com/camigomezdev/heroes-exercise.git master:gh-pages
